Window: use more actions for keyboard shortcuts
elementary/videos pull request #308
Opened 2022-06-10 02:00 UTC by danrabbit

Use actions for a few more keyboard shortcuts. Saves us some confusing manually key handling and makes Gtk4 porting easier

2022-06-10 16:34 UTC, jeremypw commented on src/Window.vala
> +        action_accelerators[ACTION_BACK] = "Back";
Do you mean "BackSpace"?  Or is there there another special "Back" key on some keyboards?

2022-06-10 16:34 UTC, jeremypw commented on src/Window.vala
> -            }
You do not seem to have implemented any actions to replace these shortcuts.

2022-06-10 16:36 UTC, jeremypw commented on src/Window.vala
> +        action_accelerators[ACTION_BACK] = "Back";
Did you mean "BackSpace"?

2022-06-10 16:36 UTC, jeremypw requested changes
See inline comments

2022-06-10 17:20 UTC, danrabbit commented on src/Window.vala
> +        action_accelerators[ACTION_BACK] = "Back";
Yeah this is for the back media key which has precedent in Switchboard here: https://github.com/elementary/switchboard/blob/b25fcb65e32fe5462fa893abd14168db652c961c/src/Application.vala#L136

2022-06-10 17:34 UTC, jeremypw commented on src/Window.vala
> +        action_accelerators[ACTION_BACK] = "Back";
OK

2022-06-11 15:47 UTC, danrabbit commented on src/Window.vala
> -            }
Oops, reverted!

2022-06-12 09:41 UTC, jeremypw approved these changes

2022-06-12 09:41 UTC, merged