Separate deck pages
elementary/videos pull request #336
Opened 2023-07-06 19:21 UTC by leolost2605

- Moves the headerbar into the separate deck pages (PlayerPage, WelcomePage, LibraryPage, EpisodesPage) and makes it flat. This allows for smoother transitions between pages and keeps Videos more inline with the general OS look
- Use `Hdy.ApplicationWindow` for rounded corners
- Do some gtk4 prep while we're here
- The rounded corners are a bit buggy on the player, #335 might fix that though

Fixes #283 
Fixes #232

Screenshots:

![Screenshot from 2023-07-06 21 19 28](https://github.com/elementary/videos/assets/106322251/b2ed50e8-0762-42ca-95c8-41b12ada60a1)
![Screenshot from 2023-07-06 21 19 51](https://github.com/elementary/videos/assets/106322251/b78e1c74-9dfb-4177-8c5a-a8a81da66aba)
![Screenshot from 2023-07-06 21 19 56](https://github.com/elementary/videos/assets/106322251/fbc38eca-b89a-460c-ac9a-0f46eb59b288)
![Screenshot from 2023-07-06 21 20 10](https://github.com/elementary/videos/assets/106322251/1f4c2d84-a3f6-4545-b92a-c1d189815aca)

2023-07-06 20:42 UTC, danirabbit requested changes
This is great! Exactly where I wanted to go with this

I agree the corner clipping this probably isn't a big deal and will be dealt with in Gtk4

2023-07-06 20:42 UTC, danirabbit commented on src/Widgets/Library/EpisodesPage.vala
> +        var autoqueue_next = new Granite.ModeSwitch.from_icon_name (
I guess if we're showing this on the player page does this need to be on the library/episodes page? I feel like it's not doing anything here

2023-07-06 20:42 UTC, danirabbit commented on src/Window.vala
> +                // header.visible = !player_page.fullscreened;
leftover comment?

2023-07-07 10:50 UTC, leolost2605 commented on src/Window.vala
> +                // header.visible = !player_page.fullscreened;
yeah 😅

2023-07-07 10:52 UTC, leolost2605 commented on src/Widgets/Library/EpisodesPage.vala
> +        var autoqueue_next = new Granite.ModeSwitch.from_icon_name (
I put it there because it was in the previous version, but I fully agree that it belongs on the player page (only). I'll update accordingly :)

2023-07-07 12:18 UTC, leolost2605 commented on src/Widgets/Library/EpisodesPage.vala
> +        var autoqueue_next = new Granite.ModeSwitch.from_icon_name (
Hmm I thought about it some more and maybe it makes more sense to put it on the episodes page only. Because currently what it does is if and only if a video was started from the episodes page it automatically puts the follow up videos into the playlist. It currently (in master) doesn't even do anything when toggled on the PlayerPage until a video gets restarted from the EpisodesPage. So either

1. We change the way it works
2. We only show it on the EpisodesPage (which would (maybe?) also make more sense when using because autoqueue only really applies to episodes and it wouldn't make sense to have it e.g. for a video which was opened using "open file" etc., or does it?)

@danirabbit any preference here?

2023-07-07 14:49 UTC, danirabbit commented on src/Widgets/Library/EpisodesPage.vala
> +        var autoqueue_next = new Granite.ModeSwitch.from_icon_name (
Ah okay. Yeah I guess it’s confusing what exactly this does so probably needs some more design thought but that can happen in a separate branch :+1:

2023-07-07 15:27 UTC, leolost2605 commented on src/Widgets/Library/EpisodesPage.vala
> +        var autoqueue_next = new Granite.ModeSwitch.from_icon_name (
I went with 2. in the meantime because IMHO keeping it on all pages brings more confusion than advantage :)

2023-07-07 15:33 UTC, merged