Move play queue to playback manager
elementary/videos pull request #366
Opened 2023-08-24 09:18 UTC by leolost2605

- Move the playqueue to the playback manager, make it a StringList and bind this list to the playlistpopover listbox
- This gets rid of the convoluted signal chains

- Remove the play () signal and instead always either play from Window or directly from the PlaybackManager. This reduces some duplicated effort when playing videos from the PlaylistPopover because previously we would create a file send the play signal in the PlaybackManager with this file causing the window to open the file try to add it to the playlist agiaing and then eventually do play_file in the PlaybackManager. Instead we now do play_file right away because we can assume that the Player is already visible when choosing a video from the playlist and we know all videos in the playlist are actually videos.

- We allow appending multiple files at once to the play queue which allows us to have IMO better toasts, so when only the video that is actually playing gets added to the playlist no toast is sent, when one additional video gets added a toast with its title is sent and when more than 2 get added a toast with n videos added to playlist gets sent.

2023-08-24 10:49 UTC, leolost2605 commented
It's all in all pretty connected but some minor changes that are required for this could be split out if necessary

2023-08-24 17:20 UTC, danirabbit commented on src/Window.vala
> +                app_notification.title = _("%u items added to playlist").printf (added);
Gotta make sure to use ngettext here since plural forms can be different across locales

2023-08-24 17:21 UTC, danirabbit commented
So excited for this. Way cleaner. Can you resolve conflicts with main please? :)

2023-08-24 20:02 UTC, leolost2605 commented on src/Window.vala
> +                app_notification.title = _("%u items added to playlist").printf (added);
I hope I did it right... never used it before 😅

2023-08-24 20:43 UTC, danirabbit requested changes
I noticed that when I add files from the playlist popover they are prepended to the list instead of added to the end of it :sweat_smile:

2023-08-24 20:43 UTC, danirabbit commented on src/Window.vala
> +                app_notification.title = ngettext ("%u item added to playlist", "%u items added to playlist", added);
Just missing the printf :)

```suggestion
                app_notification.title = ngettext ("%u item added to playlist", "%u items added to playlist", added).printf (added);
```

2023-08-24 20:43 UTC, danirabbit commented on src/Window.vala
> +            if (added == 2) {
I think instead of this we probably want:
```suggestion
            if (playback_manager.play_queue.get_n_items () == 1) {
                return;
            }

            if (added == 1) {
```

This way you don't get the toast if you're adding the first item to the queue, but you do for any subsequent adds

2023-08-24 20:43 UTC, danirabbit commented on src/Window.vala
> +            } else if (added > 2) {
With the previous suggestion

```suggestion
            } else if (added > 1) {
```

2023-08-24 20:47 UTC, danirabbit commented
> Also fixes an issue where you could play/pause, go next and previous while the player was not open. If we want we could automatically show the player instead of disabling right away?

Yeah having the play action switch to the playerpage would be pretty dope, but could wait for another branch imo

> Repeat now takes precedence of the next item in the play queue which is I think how it should be?

We could probably follow up in another branch to make sure we have "repeat all" and "repeat one" like Music has it

2023-08-25 10:26 UTC, leolost2605 commented
> I noticed that when I add files from the playlist popover they are prepended to the list instead of added to the end of it 😅

Fixed :)

2023-08-25 16:49 UTC, danirabbit approved these changes
Great improvement. Nice work! So much cleaner and better

2023-08-25 16:49 UTC, merged